### ISSUE TITLE
[Question] numba.core.errors.UnsupportedError: Use of unsupported opcode (DICT_UPDATE) found

### ISSUE THREAD

**Issue by scheung38** [Bodo-inc/Bodo-tutorial#19]
The code below worked but upon adding @bodo.jit I got back:

(.venv_file_processing_pipeline) ➜  file_processing_pipeline git:(master) ✗ python src/main.py                   
Traceback (most recent call last):
  File "$HOME/Documents/file_processing_pipeline/src/main.py", line 106, in <module>
    read_and_validate_file('train.csv')
  File "$HOME/opt/anaconda3/envs/.venv_file_processing_pipeline/lib/python3.9/site-packages/bodo/numba_compat.py", line 785, in _compile_for_args
    error_rewrite(e, 'unsupported_error')
  File "$HOMEopt/anaconda3/envs/.venv_file_processing_pipeline/lib/python3.9/site-packages/bodo/numba_compat.py", line 700, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.UnsupportedError: Use of unsupported opcode (DICT_UPDATE) found

File "src/main.py", line 73:
def read_and_validate_file(file):
    <source elided>

        new_schema = pa.DataFrameSchema({

src/main.py

```

import pandas as pd
import pandera as pa
from icecream import ic
import pycountry
from pathlib import Path
from fastapi import FastAPI

app = FastAPI()
import time
import bodo

 
@bodo.jit     
def read_and_validate_file(file):

    try:

        if Path(file).suffix == ".csv": 

            test_data = pd.read_csv('data_in/'+file)
            ic('Found csv file!')

        elif Path(file).suffix == ".xlsx":

            test_data = pd.read_excel('data_in/'+file, skiprows=1)
            ic('Found Excel file!')

        else:
            ic('Cannot determine file extension, please check')

        ic(test_data)

        data_sample = test_data.sample(n=4)

        Company = ['GOOG-Google', 'AAPL-Apple', 'TSLA-Tesla', 'NVDA-Nvidia', 'AMZN-Amazon', 'INTC-Intel', 'MSFT-Microsoft', 'ADI-Analog Devices', ]
        Deals = ['Deals-1', 'Deals-2', 'Deals-3', 'Deals-4', 'Deals-5']

        # Defining the schema
        schema = pa.DataFrameSchema({
        "DealName" : pa.Column(pa.String, checks=pa.Check.isin(
                    [deal for deal in list(Deals)]), required=True, nullable=False),
        "D1" : pa.Column(pa.Float64, required=True),
        "D2" : pa.Column(pa.Float64, nullable=True, required=False),
        "D3" : pa.Column(pa.Float64, nullable=True, required=False),
        "D4" : pa.Column(pa.Float64, nullable=True, required=False),
        "D5" : pa.Column(pa.Float64, nullable=True, required=False),
        "IsActive" : pa.Column(pa.Bool, nullable=True, required=False),
        "CountryName" : pa.Column(pa.String, checks=pa.Check.isin(
                    [country.name for country in list(pycountry.countries)]), required=True),
        "CountryCode" : pa.Column(pa.String, checks=pa.Check.isin(
                    [country.alpha_2 for country in list(pycountry.countries)]), required=True),
        "CurrencyName" : pa.Column(pa.String, checks=pa.Check.isin(
                    [currency.name for currency in list(pycountry.currencies)]), required=True),
        "CurrencyCode" : pa.Column(pa.String, checks=pa.Check.isin(
                    [currency.alpha_3 for currency in list(pycountry.currencies)]), required=True),
        "Company" : pa.Column(pa.String, checks=pa.Check.isin(
                    [company for company in list(Company)]), required=True),
        })

        example_input = schema.example(size=10)
        ic(example_input)

        new_schema = pa.DataFrameSchema({
        "RowNo" : pa.Column(pa.INT8, allow_duplicates=False),
        **schema.columns,
        "AsOfDate" : pa.Column(pa.DateTime),
        "ProcessIdentifier" : pa.Column(pa.INT32, allow_duplicates=False, nullable=False),
        "RowHash" : pa.Column(pa.INT64, allow_duplicates=False)
        })

        # Validating the data
        df_input = schema.validate(data_sample)
        ic(df_input)

        # Validating the transformed_data
        df_output = new_schema.example(size=10) # transformed_schema
        ic(df_output)
        
        df_output.to_csv('data_out/out.csv', sep=',', index=False)
        df_output.to_parquet('data_out/df_output.parquet.gzip', compression='gzip', use_deprecated_int96_timestamps=True)
        # check parquet file
        parq = pd.read_parquet('data_out/df_output.parquet.gzip')
        ic(parq)

        return 'File created in data_out/out.csv'

    except Exception as e:
        with open('error_log/error.txt', 'a') as f:
            ic(e)
            f.write(str(e)+'\n')
            return str(e)

if __name__ == '__main__':
    read_and_validate_file('train.csv')
    read_and_validate_file('train.xlsx')
```

**Comment by ehsantn** [comment]
@scheung38 Thanks for your interest in Bodo. Only supported APIs can be JITed. For example, looks like PyArrow is used in this code which is not supported. Please see the docs for the supported APIs: [docs.bodo.ai](url)
